name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize] # 当 PR 新建或更新代码时触发

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # 赋予机器人写评论的权限

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AI PR Reviewer
        uses: truongnh1992/gemini-ai-code-reviewer@v9.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-2.5-flash
          EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"
